import { expect, test } from "@playwright/test";
import fs from "node:fs/promises";
import path from "node:path";

const repoRoot = path.resolve(process.cwd(), "../..");
const proofRoot = process.env.WILQ_DASHBOARD_PROOF_DIR
  ? path.resolve(process.env.WILQ_DASHBOARD_PROOF_DIR)
  : path.join(repoRoot, ".local-lab/proof/dashboard-demo");

test.describe("WILQ dashboard marketer demo proof", () => {
  test("captures API-backed demo path with action plan and blockers", async ({ page }) => {
    const runDir = path.join(proofRoot, new Date().toISOString().replace(/[:.]/g, "-"));
    await fs.mkdir(runDir, { recursive: true });

    await page.goto("/command-center");
    await expect(page.getByRole("heading", { name: "Plan działań marketera" })).toBeVisible();
    await expect(
      page.getByRole("heading", { name: "Przejrzyj produkty z problemami w Merchant Center" })
    ).toBeVisible();
    await expect(
      page.getByRole("heading", { name: "Ułóż kolejkę refresh/merge/create dla treści SEO" })
    ).toBeVisible();
    await expect(
      page.getByRole("heading", { name: "Sprawdź jakość ruchu i landing page w GA4" })
    ).toBeVisible();
    await expect(
      page.getByRole("heading", { name: "Napraw Google Ads OAuth zanim padną wnioski o spendzie" })
    ).toBeVisible();
    await expect(
      page.getByRole("heading", { name: "Dokończ Localo access przed lokalnymi rekomendacjami" })
    ).toBeVisible();
    await expect(page.getByRole("heading", { name: "Demo dla marketera" })).toBeVisible();
    await expect(page.getByText("act_review_merchant_feed_issues").first()).toBeVisible();
    await expect(page.getByText("act_configure_google_ads_env").first()).toBeVisible();
    await page.screenshot({
      path: path.join(runDir, "01-command-center-action-plan.png"),
      fullPage: true,
    });

    await page.goto("/merchant");
    await expect(page.getByRole("heading", { name: "Merchant Center", exact: true })).toBeVisible();
    await expect(page.getByText("Merchant Center: kolejka feed/product issues")).toBeVisible();
    await expect(page.getByText(/Merchant: .*availability_updated/).first()).toBeVisible();
    await expect(page.getByRole("link", { name: "act_review_merchant_feed_issues" }).first()).toBeVisible();
    await expect(page.getByRole("link", { name: /ev_refresh_refresh_google_merchant_center/ }).first()).toBeVisible();
    await page.screenshot({
      path: path.join(runDir, "02-merchant-feed-issues.png"),
      fullPage: true,
    });

    await page.goto("/content-planner");
    await expect(page.getByRole("heading", { name: "Content Planner", exact: true })).toBeVisible();
    await expect(page.getByRole("heading", { name: "Status SEO / Content" })).toBeVisible();
    await expect(page.getByRole("link", { name: "act_prepare_content_refresh_queue" }).first()).toBeVisible();
    await page.screenshot({
      path: path.join(runDir, "03-content-planner-queue.png"),
      fullPage: true,
    });

    await page.goto("/ga4");
    await expect(page.getByRole("heading", { name: "GA4", exact: true })).toBeVisible();
    await expect(page.getByRole("heading", { name: "GA4: landing/source/campaign behavior" })).toBeVisible();
    await expect(page.getByRole("link", { name: "act_review_ga4_tracking_quality" }).first()).toBeVisible();
    await page.screenshot({
      path: path.join(runDir, "04-ga4-landing-quality.png"),
      fullPage: true,
    });

    await page.goto("/ads-doctor");
    await expect(page.getByRole("heading", { name: "Ads Doctor" })).toBeVisible();
    await expect(page.getByText("Google Ads: OAuth blokuje live metryki")).toBeVisible();
    await expect(page.getByText(/oauth_error=/).first()).toBeVisible();
    await page.screenshot({
      path: path.join(runDir, "05-ads-oauth-blocker.png"),
      fullPage: true,
    });

    await page.goto("/localo");
    await expect(page.getByRole("heading", { name: "Localo", exact: true })).toBeVisible();
    await expect(page.getByText(/LOCALO_ACCESS_TOKEN/).first()).toBeVisible();
    await expect(page.getByText(/local ranking/i)).toHaveCount(0);
    await page.screenshot({
      path: path.join(runDir, "06-localo-access-blocker.png"),
      fullPage: true,
    });

    await fs.writeFile(
      path.join(runDir, "README.md"),
      [
        "# WILQ dashboard demo proof",
        "",
        "Local browser proof generated by Playwright.",
        "",
        "- 01-command-center-action-plan.png",
        "- 02-merchant-feed-issues.png",
        "- 03-content-planner-queue.png",
        "- 04-ga4-landing-quality.png",
        "- 05-ads-oauth-blocker.png",
        "- 06-localo-access-blocker.png",
        "",
      ].join("\n"),
      "utf-8"
    );
  });
});
