from __future__ import annotations

from collections.abc import Callable, Iterable

from wilq.schemas import (
    AdsAccountCurrencyReadContract,
    AdsBlockedHandoff,
    AdsBudgetPacingReadContract,
    AdsBusinessContextReadContract,
    AdsCampaignReadContract,
    AdsCampaignTriageReadContract,
    AdsChangeHistoryReadContract,
    AdsChangeImpactReadinessContract,
    AdsCustomSegmentsReadContract,
    AdsDecisionItem,
    AdsDerivedKpiReadContract,
    AdsDiagnosticSection,
    AdsDiagnosticsResponse,
    AdsFreshnessAssessment,
    AdsImpressionShareReadContract,
    AdsKeywordMatchContextReadContract,
    AdsKeywordPlannerReadContract,
    AdsNegativeKeywordsReadContract,
    AdsOperatorSummary,
    AdsOptimizerReadinessContract,
    AdsRecommendationsReadContract,
    AdsSearchTermNgramReadContract,
    AdsSearchTermReviewSummaryContract,
    AdsSearchTermSafetyReadContract,
    AdsSearchTermsReadContract,
    ConnectorRefreshRun,
    ConnectorStatus,
)


def build_diagnostics_response(
    *,
    connector: ConnectorStatus,
    latest_refresh: ConnectorRefreshRun | None,
    live_data_available: bool,
    account_currency_read_contract: AdsAccountCurrencyReadContract,
    campaign_read_contract: AdsCampaignReadContract,
    business_context_read_contract: AdsBusinessContextReadContract,
    derived_kpi_read_contract: AdsDerivedKpiReadContract,
    budget_pacing_read_contract: AdsBudgetPacingReadContract,
    recommendations_read_contract: AdsRecommendationsReadContract,
    impression_share_read_contract: AdsImpressionShareReadContract,
    campaign_triage_read_contract: AdsCampaignTriageReadContract,
    optimizer_readiness_contract: AdsOptimizerReadinessContract,
    change_history_read_contract: AdsChangeHistoryReadContract,
    change_impact_readiness_contract: AdsChangeImpactReadinessContract,
    search_terms_read_contract: AdsSearchTermsReadContract,
    search_term_review_summary_contract: AdsSearchTermReviewSummaryContract,
    search_term_ngram_read_contract: AdsSearchTermNgramReadContract,
    search_term_safety_read_contract: AdsSearchTermSafetyReadContract,
    keyword_match_context_read_contract: AdsKeywordMatchContextReadContract,
    keyword_planner_read_contract: AdsKeywordPlannerReadContract,
    custom_segments_read_contract: AdsCustomSegmentsReadContract,
    negative_keywords_read_contract: AdsNegativeKeywordsReadContract,
    decision_queue: list[AdsDecisionItem],
    sections: list[AdsDiagnosticSection],
    blocked_handoff: AdsBlockedHandoff | None,
    strict_instruction: str,
    connector_status_label: Callable[[str], str],
    refresh_status_label: Callable[[ConnectorRefreshRun], str],
    live_data_status_label: Callable[[bool], str],
    freshness_assessment: Callable[[ConnectorRefreshRun | None], AdsFreshnessAssessment],
    operator_summary: Callable[
        [
            list[AdsDecisionItem],
            AdsCampaignReadContract,
            AdsSearchTermsReadContract,
            AdsOptimizerReadinessContract,
        ],
        AdsOperatorSummary,
    ],
    unique: Callable[[Iterable[str]], list[str]],
) -> AdsDiagnosticsResponse:
    return AdsDiagnosticsResponse(
        strict_instruction=strict_instruction,
        connector=connector,
        connector_status_label=connector_status_label(str(connector.status)),
        latest_refresh=latest_refresh,
        latest_refresh_status_label=refresh_status_label(latest_refresh)
        if latest_refresh
        else None,
        live_data_status_label=live_data_status_label(live_data_available),
        live_data_available=live_data_available,
        freshness_assessment=freshness_assessment(latest_refresh),
        account_currency_read_contract=account_currency_read_contract,
        campaign_read_contract=campaign_read_contract,
        business_context_read_contract=business_context_read_contract,
        derived_kpi_read_contract=derived_kpi_read_contract,
        budget_pacing_read_contract=budget_pacing_read_contract,
        recommendations_read_contract=recommendations_read_contract,
        impression_share_read_contract=impression_share_read_contract,
        campaign_triage_read_contract=campaign_triage_read_contract,
        optimizer_readiness_contract=optimizer_readiness_contract,
        change_history_read_contract=change_history_read_contract,
        change_impact_readiness_contract=change_impact_readiness_contract,
        search_terms_read_contract=search_terms_read_contract,
        search_term_review_summary_contract=search_term_review_summary_contract,
        search_term_ngram_read_contract=search_term_ngram_read_contract,
        search_term_safety_read_contract=search_term_safety_read_contract,
        keyword_match_context_read_contract=keyword_match_context_read_contract,
        keyword_planner_read_contract=keyword_planner_read_contract,
        custom_segments_read_contract=custom_segments_read_contract,
        negative_keywords_read_contract=negative_keywords_read_contract,
        operator_summary=operator_summary(
            decision_queue,
            campaign_read_contract,
            search_terms_read_contract,
            optimizer_readiness_contract,
        ),
        decision_queue=decision_queue,
        sections=sections,
        blocked_handoff=blocked_handoff,
        evidence_ids=unique(
            evidence_id for section in sections for evidence_id in section.evidence_ids
        ),
        action_ids=unique(action_id for section in sections for action_id in section.action_ids),
        blocker_count=sum(1 for decision in decision_queue if decision.status == "blocked"),
    )
