import { z } from "zod";

import { ActionPreviewCardViewModelSchema } from "./actions";
import {
  ConnectorRefreshRunSchema,
  ConnectorStatusSchema,
  MetricFactSchema
} from "./connectors";
import { TacticalQueueItemSchema } from "./marketing";

export const MerchantDiagnosticSectionSchema = z.object({
  id: z.string(),
  label: z.string().default(""),
  title: z.string(),
  status: z.enum(["ready", "blocked", "missing"]),
  status_label: z.string().default(""),
  summary: z.string(),
  diagnosis: z.string(),
  next_step: z.string(),
  source_connectors: z.array(z.string()),
  source_connector_labels: z.array(z.string()).default([]),
  evidence_ids: z.array(z.string()),
  evidence_summary_label: z.string().default(""),
  metric_facts: z.array(MetricFactSchema),
  tactical_items: z.array(TacticalQueueItemSchema),
  action_ids: z.array(z.string()),
  action_summary_label: z.string().default(""),
  blocked_claims: z.array(z.string()),
  blocked_claim_labels: z.array(z.string()).default([]),
  risk: z.enum(["low", "medium", "high", "critical"]),
  risk_label: z.string().default("")
});

export const MerchantIssueClusterSchema = z.object({
  id: z.string(),
  issue_type: z.string(),
  issue_type_label: z.string().nullable().optional(),
  severity: z.string(),
  severity_label: z.string().nullable().optional(),
  resolution: z.string().nullable().optional(),
  resolution_label: z.string().nullable().optional(),
  affected_attribute: z.string().nullable().optional(),
  affected_attribute_label: z.string().nullable().optional(),
  country: z.string().nullable().optional(),
  reporting_context: z.string().nullable().optional(),
  reporting_context_label: z.string(),
  product_count: z.number(),
  reported_issue_summary_label: z.string().default(""),
  count_semantics: z.literal("reported_issue_occurrences").default("reported_issue_occurrences"),
  sample_product_ids: z.array(z.string()),
  sample_titles: z.array(z.string()),
  sample_unavailable_reason: z.string().nullable().optional(),
  source_connectors: z.array(z.string()),
  evidence_ids: z.array(z.string()),
  blocked_claims: z.array(z.string()),
  action_id: z.string().nullable().optional(),
  risk: z.enum(["low", "medium", "high", "critical"]),
  risk_label: z.string().default(""),
  next_step: z.string()
});

export const MerchantDecisionItemSchema = z.object({
  id: z.string(),
  decision_type: z.enum([
    "review_issue_cluster",
    "review_feed_status",
    "review_product_state_mapping",
    "review_price_impact_readiness",
    "block_until_vendor_read"
  ]),
  decision_type_label: z.string().default(""),
  status: z.enum(["ready", "blocked", "missing"]),
  status_label: z.string().default(""),
  title: z.string(),
  summary: z.string().nullable().optional(),
  cluster_id: z.string().nullable().optional(),
  issue_cluster_ids: z.array(z.string()).default([]),
  issue_type: z.string().nullable().optional(),
  issue_type_label: z.string().nullable().optional(),
  severity: z.string().nullable().optional(),
  severity_label: z.string().nullable().optional(),
  resolution: z.string().nullable().optional(),
  resolution_label: z.string().nullable().optional(),
  affected_attribute: z.string().nullable().optional(),
  affected_attribute_label: z.string().nullable().optional(),
  country: z.string().nullable().optional(),
  reporting_context: z.string().nullable().optional(),
  reporting_context_label: z.string().nullable().optional(),
  product_count: z.number().nullable().optional(),
  issue_count: z.number().nullable().optional(),
  count_semantics: z.literal("reported_issue_occurrences").default("reported_issue_occurrences"),
  priority: z.number(),
  priority_label: z.string().default(""),
  metric_tiles: z.record(z.string(), z.union([z.string(), z.number()])).default({}),
  sample_product_ids: z.array(z.string()).default([]),
  sample_titles: z.array(z.string()).default([]),
  change_preview: z.array(z.record(z.string(), z.unknown())).default([]),
  preview_cards: z.array(ActionPreviewCardViewModelSchema).default([]),
  source_connectors: z.array(z.string()),
  source_connector_labels: z.array(z.string()).default([]),
  evidence_ids: z.array(z.string()),
  evidence_summary_label: z.string().default(""),
  metric_facts: z.array(MetricFactSchema),
  action_ids: z.array(z.string()),
  action_summary_label: z.string().default(""),
  blocked_claims: z.array(z.string()),
  blocked_claim_labels: z.array(z.string()).default([]),
  rationale: z.string(),
  next_step: z.string(),
  why_it_matters: z.string().nullable().optional(),
  operator_action: z.string().nullable().optional(),
  risk: z.enum(["low", "medium", "high", "critical"]),
  risk_label: z.string().default("")
});

export const MerchantOperatorSummarySchema = z.object({
  id: z.literal("merchant_operator_summary"),
  title: z.string(),
  summary: z.string(),
  next_step: z.string(),
  top_decision_ids: z.array(z.string()),
  top_issue_cluster_ids: z.array(z.string()),
  top_tactical_item_ids: z.array(z.string()),
  reported_issue_occurrences: z.number(),
  decision_source: z.literal("decision_queue").default("decision_queue"),
  decision_source_label: z.string().default("kolejka decyzji Merchant"),
  drilldown_source: z.literal("issue_clusters").default("issue_clusters"),
  drilldown_source_label: z.string().default("grupy problemów pliku produktowego"),
  count_semantics: z.literal("reported_issue_occurrences").default("reported_issue_occurrences"),
  count_semantics_label: z.string().default("wystąpienia problemów w raportach"),
  issue_types: z.array(z.string()),
  source_connectors: z.array(z.string()),
  source_connector_labels: z.array(z.string()).default([]),
  evidence_ids: z.array(z.string()),
  evidence_summary_label: z.string().default(""),
  action_ids: z.array(z.string()),
  action_summary_label: z.string().default(""),
  blocked_claims: z.array(z.string()),
  blocked_claim_labels: z.array(z.string()).default([]),
  metric_tiles: z.record(z.string(), z.union([z.string(), z.number()])).default({})
});

export const MerchantFreshnessAssessmentSchema = z.object({
  state: z.enum(["fresh", "stale", "missing", "blocked"]),
  state_label: z.string().default(""),
  checked_at: z.string().nullable().optional(),
  latest_refresh_id: z.string().nullable().optional(),
  latest_refresh_completed_at: z.string().nullable().optional(),
  age_hours: z.number().nullable().optional(),
  stale_after_hours: z.number(),
  requires_refresh: z.boolean(),
  summary: z.string(),
  next_step: z.string()
});

export const MerchantUnknownFactSchema = z.object({
  id: z.string(),
  title: z.string(),
  reason: z.string(),
  impact: z.string(),
  next_step: z.string(),
  blocked_claims: z.array(z.string()),
  blocked_claim_labels: z.array(z.string()).default([])
});

export const MerchantProductSampleReadinessSchema = z.object({
  status: z.enum(["ready", "blocked"]),
  status_label: z.string().default(""),
  sample_products_available: z.boolean(),
  sample_count: z.number(),
  sample_product_ids: z.array(z.string()),
  sample_product_titles: z.array(z.string()),
  sample_summary_label: z.string().default(""),
  sample_title_labels: z.array(z.string()).default([]),
  current_read_contract: z.literal("merchant_aggregate_product_statuses"),
  required_read_contracts: z.array(z.string()),
  source_endpoint: z.string(),
  summary: z.string(),
  next_step: z.string(),
  blocked_claims: z.array(z.string()),
  blocked_claim_labels: z.array(z.string()).default([])
});

export const MerchantProductPerformanceRowSchema = z.object({
  product_id: z.string(),
  title_label: z.string().default(""),
  product_reference_label: z.string().default(""),
  sample_title: z.string().nullable().optional(),
  issue_type: z.string().nullable().optional(),
  issue_type_label: z.string().nullable().optional(),
  affected_attribute: z.string().nullable().optional(),
  affected_attribute_label: z.string().nullable().optional(),
  country: z.string().nullable().optional(),
  reporting_context: z.string().nullable().optional(),
  reporting_context_label: z.string().nullable().optional(),
  source_connectors: z.array(z.string()),
  source_connector_labels: z.array(z.string()).default([]),
  evidence_ids: z.array(z.string()),
  evidence_summary_label: z.string().default(""),
  ads_product_title: z.string().nullable().optional(),
  ads_product_status: z.string().nullable().optional(),
  ads_product_status_label: z.string().default(""),
  ads_product_availability: z.string().nullable().optional(),
  ads_product_availability_label: z.string().default(""),
  ads_product_price_micros: z.number().nullable().optional(),
  ads_product_price_label: z.string().default(""),
  ads_product_currency_code: z.string().nullable().optional(),
  ads_product_previous_price_micros: z.number().nullable().optional(),
  ads_product_price_delta_micros: z.number().nullable().optional(),
  ads_product_price_delta_percent: z.number().nullable().optional(),
  ads_clicks: z.number().nullable().optional(),
  ads_clicks_label: z.string().default(""),
  ads_cost_micros: z.number().nullable().optional(),
  ads_cost_label: z.string().default(""),
  ads_conversions: z.number().nullable().optional(),
  ads_conversions_label: z.string().default(""),
  ads_conversion_value: z.number().nullable().optional(),
  ads_conversion_value_label: z.string().default(""),
  ga4_ecommerce_purchases: z.number().nullable().optional(),
  ga4_ecommerce_purchases_label: z.string().default(""),
  ga4_purchase_revenue: z.number().nullable().optional(),
  ga4_purchase_revenue_label: z.string().default(""),
  missing_metrics: z.array(z.string()),
  missing_metric_labels: z.array(z.string()).default([]),
  blocked_claims: z.array(z.string()),
  blocked_claim_labels: z.array(z.string()).default([])
});

export const MerchantProductPerformanceReadinessSchema = z.object({
  id: z.literal("merchant_product_performance_readiness"),
  status: z.enum(["ready", "blocked"]),
  status_label: z.string().default(""),
  joined_product_count: z.number(),
  merchant_sample_count: z.number(),
  ads_product_fact_count: z.number(),
  ga4_product_fact_count: z.number(),
  current_read_contracts: z.array(z.string()),
  required_read_contracts: z.array(z.string()),
  missing_read_contracts: z.array(z.string()),
  join_key_candidates: z.array(z.string()),
  sample_product_ids: z.array(z.string()),
  sample_product_summary_label: z.string().default(""),
  performance_rows: z.array(MerchantProductPerformanceRowSchema),
  source_connectors: z.array(z.string()),
  source_connector_labels: z.array(z.string()).default([]),
  evidence_ids: z.array(z.string()),
  evidence_summary_label: z.string().default(""),
  summary: z.string(),
  next_step: z.string(),
  blocked_claims: z.array(z.string()),
  blocked_claim_labels: z.array(z.string()).default([])
});

export const MerchantPriceImpactReadinessSchema = z.object({
  id: z.literal("merchant_price_impact_readiness"),
  status: z.enum(["ready", "blocked"]),
  status_label: z.string().default(""),
  products_with_current_price: z.number(),
  products_with_previous_price: z.number(),
  products_with_price_change: z.number().default(0),
  products_with_unchanged_price_history: z.number().default(0),
  products_with_performance_metrics: z.number(),
  current_read_contracts: z.array(z.string()),
  required_read_contracts: z.array(z.string()),
  missing_read_contracts: z.array(z.string()),
  change_preview: z.array(z.record(z.string(), z.unknown())).default([]),
  preview_cards: z.array(ActionPreviewCardViewModelSchema).default([]),
  source_connectors: z.array(z.string()),
  source_connector_labels: z.array(z.string()).default([]),
  evidence_ids: z.array(z.string()),
  evidence_summary_label: z.string().default(""),
  summary: z.string(),
  next_step: z.string(),
  blocked_claims: z.array(z.string()),
  blocked_claim_labels: z.array(z.string()).default([])
});

export const MerchantDiagnosticsResponseSchema = z.object({
  generated_at: z.string().nullable().optional(),
  language: z.literal("pl-PL"),
  strict_instruction: z.string(),
  connector: ConnectorStatusSchema,
  connector_status_label: z.string().default(""),
  latest_refresh: ConnectorRefreshRunSchema.nullable().optional(),
  latest_refresh_status_label: z.string().nullable().optional(),
  live_data_available: z.boolean(),
  live_data_status_label: z.string().default(""),
  product_count: z.number().nullable().optional(),
  issue_count: z.number().nullable().optional(),
  freshness_assessment: MerchantFreshnessAssessmentSchema,
  unknowns: z.array(MerchantUnknownFactSchema),
  product_sample_readiness: MerchantProductSampleReadinessSchema,
  product_performance_readiness: MerchantProductPerformanceReadinessSchema,
  price_impact_readiness: MerchantPriceImpactReadinessSchema,
  operator_summary: MerchantOperatorSummarySchema,
  issue_clusters: z.array(MerchantIssueClusterSchema),
  decision_queue: z.array(MerchantDecisionItemSchema),
  sections: z.array(MerchantDiagnosticSectionSchema),
  evidence_ids: z.array(z.string()),
  evidence_summary_label: z.string().default(""),
  source_connector_labels: z.array(z.string()).default([]),
  action_ids: z.array(z.string()),
  action_summary_label: z.string().default(""),
  blocker_count: z.number()
});


