const ga4MetricFact = {
  name: "active_users",
  metric_label: "aktywni użytkownicy",
  value: 20,
  period: "connector_refresh",
  source_connector: "google_analytics_4",
  evidence_id: "ev_refresh_ga4",
  unit: null,
  collected_at: "2026-06-17T10:00:00Z",
  freshness_state: "fresh",
  freshness_label: "odświeżone mniej niż godzinę temu"
};

const ga4TacticalItem = {
  id: "tq_ga4_landing",
  title: "GA4: sprawdź /oferta/; źródło ruchu: google / cpc",
  domain: "ga4",
  intent: "landing_page_quality",
  priority: 25,
  risk: "low",
  source_connectors: ["google_analytics_4"],
  evidence_ids: ["ev_refresh_ga4"],
  metric_facts: [ga4MetricFact],
  dimensions: { landing_page: "/oferta/", source_medium: "google / cpc" },
  diagnosis: "Landing /oferta/ wymaga sprawdzenia jakości ruchu.",
  next_step: "Sprawdź dopasowanie komunikatu i pomiar przed oceną kampanii.",
  blocked_claims: ["współczynnik konwersji", "werdykt zwrotu z reklam"],
  action_ids: ["act_review_ga4_tracking_quality"]
};

export const ga4Diagnostics = {
  generated_at: "2026-06-17T10:00:00Z",
  language: "pl-PL",
  strict_instruction: "WILQ pokazuje tylko metryki z danych źródłowych.",
  connector_status_label: "dostęp skonfigurowany",
  connector: {
    id: "google_analytics_4",
    label: "Google Analytics 4",
    status: "configured",
    configured: true,
    missing_credentials: [],
    available_credential_sources: ["repo_env"],
    freshness: { state: "fresh" },
    capabilities: {
      read: true,
      write: false,
      read_adapter: "ga4_data_api",
      mutation_adapter: null,
      action_scope: "review_only",
      blockers: ["vendor_write_not_implemented"],
      operations: ["ga4_tracking_gap"]
    },
    supported_actions: ["ga4_tracking_gap"]
  },
  latest_refresh: {
    id: "refresh_google_analytics_4_test",
    connector_id: "google_analytics_4",
    mode: "vendor_read",
    status: "completed",
    started_at: "2026-06-17T10:00:00Z",
    completed_at: "2026-06-17T10:00:01Z",
    evidence_ids: ["ev_refresh_ga4"],
    missing_credentials: [],
    checked_credentials: ["GOOGLE_APPLICATION_CREDENTIALS"],
    external_call_attempted: true,
    vendor_data_collected: true,
    metric_summary: { active_users: 20, sessions: 30 },
    summary: "Odczyt GA4 zakończony.",
    errors: [],
    redacted: true
  },
  latest_refresh_status_label: "zakończony",
  live_data_available: true,
  live_data_status_label: "metryki GA4 dostępne",
  landing_group_count: 1,
  low_engagement_count: 1,
  wordpress_match_count: 0,
  freshness_assessment: {
    state: "fresh",
    state_label: "dane świeże",
    checked_at: "2026-06-17T10:00:02Z",
    latest_refresh_id: "refresh_google_analytics_4_test",
    latest_refresh_completed_at: "2026-06-17T10:00:01Z",
    age_hours: 0,
    stale_after_hours: 48,
    requires_refresh: false,
    summary: "Ostatni odczyt danych GA4 mieści się w progu świeżości.",
    next_step: "Można użyć danych GA4 do review bez dodatkowego refreshu."
  },
  conversion_readiness_contract: {
    id: "ga4_conversion_readiness_contract",
    status: "blocked",
    status_label: "blokuje wnioski o konwersjach",
    title: "GA4: gotowość konwersji i zdarzeń kluczowych",
    summary:
      "GA4 nie dostarczył metryk konwersji ani zdarzeń kluczowych. WILQ może ocenić wyłącznie jakość ruchu; wnioski o konwersjach, przychodzie i opłacalności pozostają zablokowane.",
    conversion_metric_availability_status: "missing",
    conversion_observation_status: "zero_or_missing",
    key_event_configuration_status: "missing",
    allowed_metrics: ["conversions", "key_events", "purchase_revenue", "total_revenue", "transactions"],
    available_read_contracts: [],
    available_read_contract_labels: [],
    missing_read_contracts: [
      "conversion_or_key_event_mapping",
      "conversion_or_key_event_metric_facts"
    ],
    missing_read_contract_labels: [
      "powiązanie konwersji i zdarzeń kluczowych",
      "metryki konwersji i zdarzeń kluczowych"
    ],
    missing_read_contract_summary_label: "2 brakujące zakresy danych",
    conversion_like_metric_count: 0,
    observed_conversion_fact_count: 0,
    dimensioned_behavior_metric_count: 1,
    landing_group_count: 1,
    source_connectors: ["google_analytics_4"],
    source_connector_labels: ["GA4"],
    evidence_ids: ["ev_refresh_ga4"],
    evidence_summary_label: "1 dowód źródłowy",
    action_ids: ["act_review_ga4_tracking_quality"],
    action_summary_label: "1 akcja do sprawdzenia",
    blocked_claims: ["współczynnik konwersji", "werdykt zwrotu z reklam", "twierdzenie o przychodzie", "werdykt opłacalności"],
    blocked_claim_labels: ["współczynnik konwersji", "werdykt zwrotu z reklam", "twierdzenie o przychodzie", "werdykt opłacalności"],
    next_step:
      "Sprawdź jakość pomiaru w WILQ i potwierdź powiązanie konwersji i zdarzeń kluczowych przed wnioskami o opłacalności.",
    risk: "medium"
  },
  operator_summary: {
    id: "ga4_operator_summary",
    title: "Co marketer ma sprawdzić teraz w jakości ruchu",
    summary:
      "WILQ pokazuje grupy ruchu do kontroli stron wejścia, źródeł i kampanii. Brak metryk konwersji oznacza, że nie wolno wyciągać wniosków o werdykcie zwrotu z reklam, twierdzeniu o przychodzie, spadku konwersji ani winie kampanii.",
    next_step:
      "Przejdź przez najważniejsze decyzje GA4, oddziel problem pomiaru od problemu jakości ruchu i sprawdź propozycję w WILQ tylko jako sprawdzenie bez zapisu.",
    top_decision_ids: ["ga4_decision_tq_ga4_not_set", "ga4_decision_tq_ga4_landing"],
    measurement_issue_count: 1,
    wordpress_missing_count: 1,
    conversion_readiness_status: "blocked",
    source_connectors: ["google_analytics_4"],
    source_connector_labels: ["GA4"],
    evidence_ids: ["ev_refresh_ga4"],
    evidence_summary_label: "1 dowód źródłowy",
    action_ids: ["act_review_ga4_tracking_quality"],
    action_summary_label: "1 akcja do sprawdzenia",
    blocked_claims: ["współczynnik konwersji", "werdykt zwrotu z reklam", "twierdzenie o przychodzie", "werdykt opłacalności"],
    blocked_claim_labels: ["współczynnik konwersji", "werdykt zwrotu z reklam", "twierdzenie o przychodzie", "werdykt opłacalności"]
  },
  decision_queue: [
    {
      id: "ga4_decision_tq_ga4_not_set",
      decision_type: "fix_measurement",
      decision_type_label: "problem pomiaru",
      title: "GA4: napraw pomiar - brak strony wejścia w raporcie",
      status: "blocked",
      status_label: "zablokowane",
      priority: 11,
      metric_tiles: {},
      landing_page: "(not set)",
      landing_page_label: "brak strony wejścia w raporcie",
      source_medium: "google / organic",
      source_medium_label: "google / organic",
      campaign_name: "(organic)",
      campaign_name_label: "(organic)",
      wordpress_match: null,
      wordpress_match_label: null,
      wordpress_match_confidence: null,
      wordpress_match_confidence_label: null,
      wordpress_content_url: null,
      source_connectors: ["google_analytics_4"],
      source_connector_labels: ["GA4"],
      evidence_ids: ["ev_refresh_ga4"],
      evidence_summary_label: "1 dowód źródłowy",
      metric_facts: [],
      action_ids: ["act_review_ga4_tracking_quality"],
      action_summary_label: "1 akcja do sprawdzenia",
      blocked_claims: ["werdykt zwrotu z reklam", "spadek konwersji"],
      blocked_claim_labels: ["werdykt zwrotu z reklam", "spadek konwersji"],
      rationale:
        "GA4 nie zwraca strony wejścia, więc ten wiersz jest problemem pomiaru.",
      next_step:
        "Sprawdź stronę wejścia, źródło i medium, UTM-y oraz konfigurację raportu przed oceną kampanii albo strony.",
      risk: "high",
      risk_label: "wysokie ryzyko"
    },
    {
      id: "ga4_decision_tq_ga4_landing",
      decision_type: "review_landing_mapping",
      decision_type_label: "sprawdzenie strony wejścia",
      title: "Sprawdź stronę wejścia: /oferta/",
      status: "blocked",
      status_label: "zablokowane",
      priority: 31,
      metric_tiles: { aktywni: 20, sesje: 30, zaangażowanie: "12.5%" },
      landing_page: "/oferta/",
      landing_page_label: "/oferta/",
      source_medium: "google / cpc",
      source_medium_label: "google / cpc",
      campaign_name: "Ekologus Ogólna",
      campaign_name_label: "Ekologus Ogólna",
      wordpress_match: "missing",
      wordpress_match_label: "niepotwierdzone w WordPress",
      wordpress_match_confidence: "missing",
      wordpress_match_confidence_label: "dopasowanie niepotwierdzone",
      wordpress_content_url: null,
      source_connectors: ["google_analytics_4"],
      source_connector_labels: ["GA4"],
      evidence_ids: ["ev_refresh_ga4"],
      evidence_summary_label: "1 dowód źródłowy",
      metric_facts: [ga4MetricFact],
      action_ids: ["act_review_ga4_tracking_quality"],
      action_summary_label: "1 akcja do sprawdzenia",
      blocked_claims: ["współczynnik konwersji", "werdykt zwrotu z reklam", "twierdzenie o przychodzie", "werdykt opłacalności"],
      blocked_claim_labels: ["współczynnik konwersji", "werdykt zwrotu z reklam", "twierdzenie o przychodzie", "werdykt opłacalności"],
      rationale:
        "GA4 widzi ruch na stronie wejścia /oferta/, ale Spis treści WordPress nie potwierdza dopasowania URL.",
      next_step:
        "Sprawdź stronę wejścia i dopiero potem oceniaj dopasowanie komunikatu albo jakość ruchu.",
      risk: "medium",
      risk_label: "średnie ryzyko"
    }
  ],
  sections: [
    {
      id: "ga4_landing_behavior",
      label: "Jakość ruchu ze stron wejścia",
      title: "GA4: jakość ruchu ze stron wejścia",
      status: "ready",
      status_label: "gotowe",
      summary: "WILQ ma 1 grupę stron wejścia, źródeł ruchu i kampanii oraz 1 metrykę GA4.",
      diagnosis: "Fakty zachowania z GA4 pozwalają wskazać strony wejścia do kontroli jakości ruchu.",
      next_step: "Najpierw sprawdź grupy z niskim zaangażowaniem.",
      source_connectors: ["google_analytics_4"],
      source_connector_labels: ["GA4"],
      evidence_ids: ["ev_refresh_ga4"],
      evidence_summary_label: "1 dowód źródłowy",
      metric_facts: [ga4MetricFact],
      tactical_items: [ga4TacticalItem],
      action_ids: ["act_review_ga4_tracking_quality"],
      action_summary_label: "1 akcja do sprawdzenia",
      blocked_claims: ["współczynnik konwersji", "werdykt zwrotu z reklam", "twierdzenie o przychodzie"],
      blocked_claim_labels: ["współczynnik konwersji", "werdykt zwrotu z reklam", "twierdzenie o przychodzie"],
      risk: "low",
      risk_label: "niskie ryzyko"
    },
    {
      id: "ga4_tracking_readiness",
      label: "Gotowość pomiaru konwersji",
      title: "GA4: gotowość pomiaru konwersji",
      status: "missing",
      status_label: "metryki konwersji niepotwierdzone",
      summary: "WILQ ma 1 metrykę zachowania i 0 metryk konwersji albo kluczowych zdarzeń.",
      diagnosis: "Aktualne dane wspierają review jakości ruchu, ale nie dowodzą konwersji.",
      next_step: "Sprawdź propozycję w WILQ i zatrzymaj wnioski o konwersjach bez metryk.",
      source_connectors: ["google_analytics_4"],
      source_connector_labels: ["GA4"],
      evidence_ids: ["ev_refresh_ga4"],
      evidence_summary_label: "1 dowód źródłowy",
      metric_facts: [ga4MetricFact],
      tactical_items: [ga4TacticalItem],
      action_ids: ["act_review_ga4_tracking_quality"],
      action_summary_label: "1 akcja do sprawdzenia",
      blocked_claims: ["spadek konwersji", "diagnoza lejka"],
      blocked_claim_labels: ["spadek konwersji", "diagnoza lejka"],
      risk: "medium",
      risk_label: "średnie ryzyko"
    }
  ],
  evidence_ids: ["ev_refresh_ga4", "ev_refresh_ga4_tracking_review", "ev_refresh_ga4_safety"],
  evidence_summary_label: "3 dowody źródłowe",
  source_connector_labels: ["GA4"],
  action_ids: ["act_review_ga4_tracking_quality"],
  action_summary_label: "1 akcja do sprawdzenia",
  blocker_count: 1,
  decision_blocker_count: 1
};
